# Generated by Django 5.2 on 2025-04-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('loan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.bookloan')),
                ('fine_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bookloan',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.borrower'),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
            options={
                'unique_together': {('isbn', 'author')},
            },
        ),
    ]
